version: '3'

services:

  app:
    build: ./
    container_name: 'app'
    ports:
      - "7070:8080"
    depends_on:
      - db

  db:
    image: 'postgres:alpine'
    container_name: 'db'
    ports:
      - "6543:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=survey_db'
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'

volumes:
  postgresql_data: