module-name: Survey system
api-version: 1.0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/survey_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: warn

jwt:
  secret: SECRET
  issuer: user_survey_api
  subject: user_details
  claim: username
  expirationTimeSec: 36000000

