create table credential
(
    id       bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password varchar(255) not null default ('$2a$12$IfMP/bRxr2FD1Ocvh/aftel8u/HmgInaWiSO71Nsh2e1xxwBcRc4a'), -- <password>
    role     varchar(255) not null default ('USER')
);

create table survey
(
    id          bigint generated by default as identity primary key,
    title       varchar(255) not null unique,
    start_date  date         not null,
    end_date    date,
    description varchar(255)
);

create table question
(
    id        bigint generated by default as identity primary key,
    survey_id bigint references survey (id),
    type      varchar(255) not null,
    text      varchar(255) not null
);

create table usr
(
    id    bigint generated by default as identity primary key,
    name  varchar(255) default (null),
    email varchar(255) default (null)
);

create table usr_survey
(
    usr_id    bigint references usr (id),
    survey_id bigint references survey (id),
    primary key (usr_id, survey_id)
);
