create type role_type as enum('ADMIN', 'USER');

create table credential
(
    id       bigint generated by default as identity primary key,
    username text not null unique,
    password text not null default ('$2a$12$IfMP/bRxr2FD1Ocvh/aftel8u/HmgInaWiSO71Nsh2e1xxwBcRc4a'), -- <password>
    role     role_type not null default ('USER')
);

create table survey
(
    id          bigint generated by default as identity primary key,
    title       text not null unique,
    start_date  date default now(),
    end_date    date,
    description text
);

create type question_type AS ENUM ('TEXT', 'ONE_OPTION', 'MULTIPLE_OPTIONS');

create table question
(
    id        bigint generated by default as identity primary key,
    survey_id bigint references survey (id),
    type      question_type not null,
    text      text          not null
);

create table option
(
    id          bigint generated by default as identity primary key,
    question_id bigint references question (id),
    text        text not null
);

create table usr
(
    id    bigint generated by default as identity primary key,
    name  text default (null),
    email text default (null)
);

create table answer
(
    id          bigint generated by default as identity primary key,
    usr_id      bigint references usr (id),
    survey_id   bigint references survey (id),
    question_id bigint references question (id),
    answer      text default (null)
);