--liquibase formatted sql

--changeset igorchebotar:1
create table option
(
    id          bigint generated by default as identity primary key,
    question_id bigint references question (id),
    text        text not null
);