--liquibase formatted sql

--changeset igorchebotar:1
create type role_type as enum('ADMIN', 'USER');

--changeset igorchebotar:2
create table credential
(
    id       bigint generated by default as identity primary key,
    username text not null unique,
    password text not null default ('$2a$12$IfMP/bRxr2FD1Ocvh/aftel8u/HmgInaWiSO71Nsh2e1xxwBcRc4a'), -- <password>
    role     role_type not null default ('USER')
);