--liquibase formatted sql

--changeset igorchebotar:1
create type question_type AS ENUM ('TEXT', 'ONE_OPTION', 'MULTIPLE_OPTIONS');

--changeset igorchebotar:2
create table question
(
    id        bigint generated by default as identity primary key,
    survey_id bigint references survey (id),
    type      question_type not null,
    text      text          not null
);