--liquibase formatted sql

--changeset igorchebotar:1
create table survey
(
    id          bigint generated by default as identity primary key,
    title       text not null unique,
    start_date  date default now(),
    end_date    date,
    description text
);