--liquibase formatted sql

--changeset igorchebotar:1
create table answer
(
    id          bigint generated by default as identity primary key,
    usr_id      bigint references usr (id),
    survey_id   bigint references survey (id),
    question_id bigint references question (id),
    answer      text default (null)
);